### ISSUE TITLE
The project cannot build

### ISSUE THREAD

**Issue by 00rain00** [ColinEberhardt/RWTwitterInstant#3]
There are many syntax error in the project. 
Please fix it.

**Comment by wzbozon** [comment]
Change podfile to:

```
platform :ios, '10.0'

target 'TwitterInstant' do
    pod 'ReactiveCocoa', '2.1.8'
    pod 'LinqToObjectiveC', '2.0.0'
end
```

Change this and it will build on:

```
//#import "RACEXTScope.h"
#import <ReactiveCocoa/RACEXTScope.h>
```

**Comment by wzbozon** [comment]
Also to make images load one should add to Info.plist this: 

> App Transport Security Settings / Allow Arbitrary Loads = YES

**Comment by ColinEberhardt** [comment]
@wzbozon did your pull request #5 fix these issues?

**Comment by wzbozon** [comment]
@ColinEberhardt yes

**Comment by ColinEberhardt** [comment]
Thanks - much appreciated
